### ISSUE TITLE
EMFILE when using docker

### ISSUE THREAD

**Issue by EdenCoder** [Danielv123/factorioClusterio#111]
```
Error: watch ./instances/world1/script-output/output.txt EMFILE
    at exports._errnoException (util.js:1034:11)
    at FSWatcher.start (fs.js:1400:19)
    at Object.fs.watch (fs.js:1426:11)
    at instanceManagement (/factorioClusterio/client.js:487:5)
    at Rcon.<anonymous> (/factorioClusterio/client.js:268:4)
    at emitNone (events.js:86:13)
    at Rcon.emit (events.js:188:7)
    at Rcon.<anonymous> (/factorioClusterio/node_modules/simple-rcon/lib/rcon.js:48:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
```

when running the instance, I changed a few things from the docker logic specified; eg you should be using the master volume instead of `/srv/...`, eg:

`sudo docker run --name clusterio-slave -e MODE=client -e INSTANCE=world1 -v [volume name from master]:/factorioClusterio/instances -p 1235:34167 -it --restart=unless-stopped danielvestol/clusterio`

**Comment by Danielv123** [comment]
I should probably mention that I never got the client mode to work in docker, although later additions may have fixed some of what was wrong with it (or broken it completely).

EMFILE means there are too many files open apparently. I have no idea what to do about it, apparently it is possible to increase the number of file descriptors?

Here is a newer dockerfile written by another guy that I never got the time to test. If it works better, feel free to submit it as a PR

https://drive.google.com/uc?id=17RkWUNM5L0AsYVg5CGQ3yzlWiz_J9DRV

**Comment by EdenCoder** [comment]
This was resolved by:

```
sysctl -w fs.inotify.max_user_instances=81920
```
