### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Trapton** [Danielv123/factorioClusterio#116]
My Setup is:

Windows Server 2016 / Node.js 8.11.3
Factorio 0.16.36-2 (Last Stable)
Clusterio:
->Mainserver
->Farmserver

On my Farmserver I got this problem in the consolewindow (results in a huge gamelag).
But only on the farm server, but we also started yesterday and are currently playing more on this server.

RCON failed, server might be paused or shutting down
RCON failed, server might be paused or shutting down
(node:2372) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at factorioClusterio\client.js:629:30
    at messageInterfaceInternal (factorioClusterio\client.js:95:5)
    at <anonymous>
(node:2372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
RCON failed, server might be paused or shutting down
RCON failed, server might be paused or shutting down
RCON failed, server might be paused or shutting down
RCON failed, server might be paused or shutting down

**Comment by Danielv123** [comment]
So for some reason the RCON library is throwing errors instead of giving command return values. Does it stop (even temporarily) from restarting that server?

Could you try uncommenting client.js line 92 and see if the logs produce any more stacktraces?

Could you post your configuration and /instances/Farmserver/factorio-current.log file? I am particularily interested in the part where it opens the RCON server.

**Comment by Danielv123** [comment]
Closing as there is not enough information to investigate.
