### ISSUE TITLE
InitializationError: First argument must be an abstract-leveldown compliant store

### ISSUE THREAD

**Issue by EdenCoder** [Danielv123/factorioClusterio#134]
I built out a new Docker container for everything, installing from master and downloading the most recent factorio.

However when starting `master` im getting the following:

```
Generated new master authentication private key!

/factorioClusterio/node_modules/levelup/lib/levelup.js:53
    throw error
    ^
InitializationError: First argument must be an abstract-leveldown compliant store
    at new LevelUP (/factorioClusterio/node_modules/levelup/lib/levelup.js:49:13)
    at LevelUP (/factorioClusterio/node_modules/levelup/lib/levelup.js:33:12)
    at Function.Model.initStore (/factorioClusterio/node_modules/linvodb3/lib/model.js:79:100)
    at new Model (/factorioClusterio/node_modules/linvodb3/lib/model.js:52:35)
    at Object.<anonymous> (/factorioClusterio/master.js:237:12)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

According to the docs, this is something they may have updated recently.

**Comment by Gerkiz** [comment]
This occurs because linvodb3 is installed with the wrong version.
To fix this, simply do the following or add it to the Dockerfile:
 `rm -f node_modules/linvodb3/` and then install the correct version with `npm install linvodb3@3.25.1`

**Comment by EdenCoder** [comment]
Perfect cheers

**Comment by Danielv123** [comment]
linvodb is now totally removed from the install, since a few months ago, so this is no longer an issue.
