### ISSUE TITLE
PayloadTooLargeError: too many parameters

### ISSUE THREAD

**Issue by MacWaffel** [Danielv123/factorioClusterio#97]
I'm trying to build up a massively moded factorio server setup with clusterio.
But everytime i add the mods and start  the client server, the master starts to throw PayloadTooLargeError: too many parameters. Only with vanilla everything works fine.

Master console output:
```
D:\FactorioServer\factorioClusterio>node master.js
loading slaves from database/slaves.json
loading items from database/items.json
Listening on port 8080...
remoteMap | SOCKET registered map provider for 1577860422
SOCKET | Created new wsSlave: 1577860422
Slave registered: 00-FF-F8-A2-A1-3A : 44580 at localhost with name icania
Slave registered: 00-FF-F8-A2-A1-3A : 44580 at localhost with name icania
PayloadTooLargeError: too many parameters
    at queryparse (D:\FactorioServer\factorioClusterio\node_modules\body-parser\lib\types\urlencoded.js:151:13)
    at parse (D:\FactorioServer\factorioClusterio\node_modules\body-parser\lib\types\urlencoded.js:75:9)
    at D:\FactorioServer\factorioClusterio\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (D:\FactorioServer\factorioClusterio\node_modules\raw-body\index.js:224:16)
    at done (D:\FactorioServer\factorioClusterio\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (D:\FactorioServer\factorioClusterio\node_modules\raw-body\index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
Updating slave icania: 00-FF-F8-A2-A1-3A : 44580 at localhost {"UPS":"60"}
Slave registered: 00-FF-F8-A2-A1-3A : 44580 at localhost with name icania
PayloadTooLargeError: too many parameters
    at queryparse (D:\FactorioServer\factorioClusterio\node_modules\body-parser\lib\types\urlencoded.js:151:13)
    at parse (D:\FactorioServer\factorioClusterio\node_modules\body-parser\lib\types\urlencoded.js:75:9)
    at D:\FactorioServer\factorioClusterio\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (D:\FactorioServer\factorioClusterio\node_modules\raw-body\index.js:224:16)
    at done (D:\FactorioServer\factorioClusterio\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (D:\FactorioServer\factorioClusterio\node_modules\raw-body\index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
Slave registered: 00-FF-F8-A2-A1-3A : 44580 at localhost with name icania
PayloadTooLargeError: too many parameters
    at queryparse (D:\FactorioServer\factorioClusterio\node_modules\body-parser\lib\types\urlencoded.js:151:13)
    at parse (D:\FactorioServer\factorioClusterio\node_modules\body-parser\lib\types\urlencoded.js:75:9)
    at D:\FactorioServer\factorioClusterio\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (D:\FactorioServer\factorioClusterio\node_modules\raw-body\index.js:224:16)
    at done (D:\FactorioServer\factorioClusterio\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (D:\FactorioServer\factorioClusterio\node_modules\raw-body\index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
Ctrl-C...
saving to slaves.json
saving to items.json
```

Client console output:
```
D:\FactorioServer\factorioClusterio>node client.js start icania
Deleting .tmp.zip files
Deleting logs
instances\icania\mods\Advanced-Electric-v16_0.1.8.zip
instances\icania\mods\AfraidOfTheDark_1.0.20.zip
instances\icania\mods\air-filtering-patched_0.6.15.zip
instances\icania\mods\angelsaddons-oresilos_0.4.0.zip
instances\icania\mods\angelsaddons-petrotrain_0.3.2.zip
instances\icania\mods\angelsaddons-pressuretanks_0.3.0.zip
instances\icania\mods\angelsaddons-warehouses_0.3.0.zip
instances\icania\mods\angelsbioprocessing_0.5.6.zip
instances\icania\mods\angelsindustries_0.1.0.zip
instances\icania\mods\angelsinfiniteores_0.7.3.zip
instances\icania\mods\angelspetrochem_0.7.8.zip
instances\icania\mods\angelsrefining_0.9.11.zip
instances\icania\mods\angelssmelting_0.4.3.zip
instances\icania\mods\AtomicArtillery_0.1.5.zip
instances\icania\mods\beautiful_bridge_railway_0.1.3.zip
instances\icania\mods\BigBags_1.0.29.zip
instances\icania\mods\BigStorageTank_0.0.5.zip
instances\icania\mods\bobassembly_0.16.1.zip
instances\icania\mods\bobclasses_0.16.1.zip
instances\icania\mods\bobelectronics_0.16.0.zip
instances\icania\mods\bobenemies_0.16.0.zip
instances\icania\mods\bobgreenhouse_0.16.0.zip
instances\icania\mods\bobinserters_0.16.8.zip
instances\icania\mods\boblibrary_0.16.5.zip
instances\icania\mods\boblogistics_0.16.22.zip
instances\icania\mods\bobmining_0.16.0.zip
instances\icania\mods\bobmodules_0.16.0.zip
instances\icania\mods\bobores_0.16.2.zip
instances\icania\mods\bobplates_0.16.3.zip
instances\icania\mods\bobpower_0.16.4.zip
instances\icania\mods\bobrevamp_0.16.2.zip
instances\icania\mods\bobtech_0.16.5.zip
instances\icania\mods\bobvehicleequipment_0.16.2.zip
instances\icania\mods\bobwarfare_0.16.6.zip
instances\icania\mods\ChangeMapSettings_2.0.0.zip
instances\icania\mods\ChargeTransmission_0.6.0.zip
instances\icania\mods\Clowns-Extended-Minerals_1.0.7.zip
instances\icania\mods\Clowns-Nuclear_1.1.3.zip
instances\icania\mods\Clowns-Processing_1.2.6.zip
instances\icania\mods\Clowns-Science_1.0.3.zip
instances\icania\mods\clusterio_1.11.6.zip
instances\icania\mods\Dectorio_0.8.7.zip
instances\icania\mods\ElectricTrain_0.16.4.zip
instances\icania\mods\Epic-Artillery-Sounds_1.0.0.zip
instances\icania\mods\extendedangels_0.1.1.zip
instances\icania\mods\fewerTrees_0.2.4.zip
instances\icania\mods\Geothermal_1.0.80.zip
instances\icania\mods\HeavyTank_0.0.5.zip
instances\icania\mods\LoaderRedux_1.2.5.zip
instances\icania\mods\miniloader_1.5.20.zip
instances\icania\mods\mod-list.json
instances\icania\mods\mod-settings.dat
instances\icania\mods\ModuleInserter_3.0.2.zip
instances\icania\mods\MoreRepairPacks_0.1.1.zip
instances\icania\mods\Nanobots_2.0.2.zip
instances\icania\mods\only-smelting_0.1.6.zip
instances\icania\mods\PersonalTeleporter_0.3.0.zip
instances\icania\mods\reverse-factory_5.1.3.zip
instances\icania\mods\ShinyAngelGFX_0.16.8.zip
instances\icania\mods\ShinyBobGFX_0.16.19.zip
instances\icania\mods\ShinyIcons_0.16.18.zip
instances\icania\mods\skan-radio-telemetry_1.1.4.zip
instances\icania\mods\Slower_Quickreplace_0.9.0.zip
instances\icania\mods\spawn-belt_1.0.7.zip
instances\icania\mods\steinios_unlasting_oil_0.16.2.zip
instances\icania\mods\Turret-Shields_0.16.20.zip
instances\icania\mods\upgrade-planner_1.5.3.zip
Clusterio | Moving shared mods from sharedMods/ to instance/mods...
Clusterio | Moving instance specific mods from instance/instanceMods to instance/mods...
Clusterio | RCON Connected!
Clusterio | RCON Authenticated!
Started instanceManagement();
Clusterio | Registered file subscription on ./instances/icania/script-output/inventoryImports.txt
Clusterio | Loaded plugin inventoryImports
Clusterio | Loaded plugin remoteCommands
Clusterio | Registered file subscription on ./instances/icania/script-output/remoteMap.txt
Clusterio | Loaded plugin remoteMap
Clusterio | Registered file subscription on ./instances/icania/script-output/researchSync.txt
Clusterio | Loaded plugin researchSync
Clusterio | Registered file subscription on ./instances/icania/script-output/UPSdisplay.txt
Clusterio | Loaded plugin UPSdisplay
SOCKET | registering slave!
Registered our precense with master localhost at 1525902606312
Registered our precense with master localhost at 1525902606711
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
master has mod
Clusterio | inventoryImports | Stdout: Polling inventories

Registered our precense with master localhost at 1525902616305
Registered our precense with master localhost at 1525902617706
Caught interrupt signal
Clusterio | RCON Disconnected!
```

**Comment by Danielv123** [comment]
Does the latest dev branch fix work for you? `git checkout dev`, run the master once, then copy the secret-api-token.txt files contents into the token field in config.json

**Comment by MacWaffel** [comment]
Yes, the latest dev branch works fine.

Thank you!
